countries = filter(lambda c: sum([medals_by_country[c][m] for m in medals_by_country[c].keys()]), countries)
countries = sorted(countries, key=lambda c: -sum([medals_by_country[c][m] for m in medals_by_country[c].keys()]))
gx = array([medals_by_country[c]["gold"] for c in countries])
sx = array([medals_by_country[c]["silver"] for c in countries])
bx = array([medals_by_country[c]["bronze"] for c in countries])
x = range(len(countries))

plt.figure(figsize=(10, 6))
plt.bar(x, gx, align="center", color=gold_color, label="Zlato")
plt.bar(x, sx, align="center", bottom=gx, color=silv_color, label="Srebor")
plt.bar(x, bx, align="center", bottom=gx+sx, color=bron_color, label="Bron")
plt.xlim(-0.5, len(x)-0.5)
plt.legend()
plt.xticks(x)
plt.yticks(range(0, 25, 2))
plt.gca().set_xticklabels(countries, rotation=90)
plt.ylabel("St. medalj")
plt.show()

